### ISSUE TITLE
Intentional New Lines Removed From `<code>` Blocks

### ISSUE THREAD

**Issue by AristurtleDev** [ap0llo/mddocs#245] opened 2023-02-18 21:35 UTC
I have the following `<code>` blocks inside an `<example>` block :

```cs
/// <example>
///     The following example demonstrates how to create a <see cref="Sprite"/> using a
///     <see cref="MonoGame.Aseprite.Content.Processors.SpriteProcessor"/>.
///     <code>
///     //  Load an Aseprite file
///     AsepriteFile aseFile = AsepriteFile.Load("path-to-file");
///     
///     //  Use the SpriteProcessor to create a Sprite
///     Sprite sprite = SpriteProcessor.Process(GraphicsDevice, aseFile, frameIndex: 0);
///     </code>
///     
///     The following example demonstrates how to create a <see cref="Sprite"/> from a <see cref="TextureAtlas"/>.
///     <code>
///     //  Load an Aseprite File
///     AsepriteFile aseFile = AsepriteFile.Load("path-to-file")
///     
///     //  Create a TextureAtlas from the AsepriteFile using the TextureAtlasProcessor
///     TextureAtlas atlas = TextureAtlasProcessor.Process(GraphicsDevice, aseFile);
///     
///     //  Create a Sprite from region 0 in the TextureAtlas
///     Sprite sprite = atlas.CreateSprite(regionIndex: 0);
///     </code>
///     
///     The following example demonstrates how to create a <see cref="Sprite"/> from a <see cref="SpriteSheet"/>.
///     <code>
///     //  Load an Aseprite File
///     AsepriteFile aseFile = AsepriteFile.Load("path-to-file")
///     
///     //  Create a SpriteSheet from the AsepriteFile using the SpriteSheetProcessor
///     SpriteSheet spriteSheet = SpriteSheetProcessor.Process(GraphicsDevice, aseFile);
///     
///     //  Create a Sprite from region 0 in the SpriteSheet
///     Sprite sprite = spriteSheet.CreateSprite(regionIndex: 0);
///     </code>
/// </example>
```

when generated using mddocs it produces the following output

<img width="905" alt="Screen Shot 2023-02-18 at 4 09 13 PM" src="https://user-images.githubusercontent.com/103014489/219899601-b6768e73-c1cb-4a00-8e7a-858f4c187443.png">

Notice that within the generated markdown code blocks, the intentional new lines added in the XML are stripped out.  If possible, it would be preferred to have new lines within the `<code>...</code>` sections preserved for formatting.

**Comment by AristurtleDev** [comment] 2023-02-18 21:40
If I had to make a guess, I'd say it was [this line in the `TrimLines` method](https://github.com/ap0llo/mddocs/blob/master/src/MdDocs.ApiReference/Model/XmlDocs/XmlDocsReader.cs#L442) that's doing it.

Looks like that's used by both `TrimText` and `TrimCode`.  But empty new lines in code vs text would be preferred for formatting the code examples.

**Comment by ap0llo** [comment] 2023-02-25 21:27
Yes, I agree, blank lines in `<code>` blocks should be retained in the output.

Thanks for reporting

**Comment by ap0llo** [comment] 2023-02-25 23:51
@AristurtleDev This issue should be fixed with version 0.6.30-pre or newer which is available in the prerelease [MyGet feed](https://www.myget.org/feed/ap0llo-mddocs/package/nuget/Grynwald.MdDocs). Could you please verify this resolves the issue? 

If the issue is resolved, I'll push out the update to nuget.org

**Comment by AristurtleDev** [comment] 2023-02-26 02:06
I can check in a few and let you know

**Comment by AristurtleDev** [comment] 2023-02-26 04:20
@ap0llo Just checked using version `0.6.37-pre` from the MyGet feed and the issue is resolved.  Thank you.

**Comment by ap0llo** [comment] 2023-02-26 12:00
Version 0.6.39 is now available on nuget.org

**Closed by ap0llo** 2023-02-26 12:00 UTC
Labels: bug
